### ISSUE TITLE
Problem with Drupal core alpha10

### ISSUE THREAD

**Issue by vacho** [kalabro/drupal-examples-legacy#2]
In this path: http://www.misitio.com/admin/config/hello

this message appear

Recoverable fatal error: Argument 2 passed to Drupal\hello\Form\HelloConfigForm::__construct() must be an instance of Drupal\Core\Config\Context\ContextInterface, none given, called in /var/www/alpha/core/lib/Drupal/Core/Form/ConfigFormBase.php on line 42 and defined in Drupal\hello\Form\HelloConfigForm->__construct() (line 29 of modules/hello/lib/Drupal/hello/Form/HelloConfigForm.php).

I study this module in drupal 8 Alpha 10 release.

**Comment by kalabro** [comment]
Hello, @vacho! It is because this module is outdated (see last commit date). It needs rewrite for current Drupal 8 head. If you are interested, any pull requests are welcome.
